### ISSUE TITLE
Data paths are all in Windows style with back slashes

### ISSUE THREAD

**Issue by moshix** [arda-guler/orbitSim3D#3]
Love your work. Unfortunately,  I don't have windows, so all the back slaches references don't work on Linux or on Macos. 

thanks a lot.

**Comment by arda-guler** [comment]
Thank you.
Does 8ea628898f08ff97a2595d0c059f0ae0cf30e6fe fix the issue?

**Comment by arda-guler** [comment]
Tested on Linux Mint 21 Xfce, 8cce4847443899459bb676215b643e7887a70253 should solve the problem. Closing.
@moshix , feel free to reopen if something is still broken.
